import React from 'react';
import { Link } from 'react-router-dom';

const TermsOfService = () => {
  return (
    <div className="min-h-screen bg-white dark:bg-gray-900 text-gray-800 dark:text-gray-200">
      <div className="max-w-4xl mx-auto px-4 py-16">
        <Link to="/" className="inline-flex items-center mb-8 text-blue-600 dark:text-blue-400 hover:underline">
          <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
          </svg>
          Back to Home
        </Link>
        
        <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
        
        <div className="space-y-8">
          <section>
            <h2 className="text-2xl font-semibold mb-4">Introduction</h2>
            <p className="mb-4">
              Welcome to LINE.UP. By accessing or using our application, you agree to be bound by these Terms of Service. Please read them carefully.
            </p>
            <p>
              LINE.UP is a free productivity application that provides task management, focus timer, and AI assistance features to help you organize your work and improve productivity.
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-semibold mb-4">Account Registration</h2>
            <p className="mb-4">
              To use LINE.UP, you need to create an account. You are responsible for:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Providing accurate information during registration</li>
              <li>Maintaining the security of your account credentials</li>
              <li>All activities that occur under your account</li>
            </ul>
          </section>
          
          <section>
            <h2 className="text-2xl font-semibold mb-4">Free Service</h2>
            <p className="mb-4">
              LINE.UP is currently offered as a free service. We reserve the right to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Modify or discontinue any feature of the service</li>
              <li>Limit usage or storage capacity</li>
              <li>Change the terms of the free offering</li>
            </ul>
            <p>
              We will make reasonable efforts to notify users of significant changes to the service.
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-semibold mb-4">User Content</h2>
            <p className="mb-4">
              You retain ownership of any content you create or upload to LINE.UP. By using our service, you grant us a license to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Store and display your content as necessary to provide the service</li>
              <li>Use anonymized data for improving our service</li>
            </ul>
            <p>
              You are solely responsible for the content you create and share through our service.
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-semibold mb-4">AI Assistant Usage</h2>
            <p className="mb-4">
              Our AI Assistant is powered by DeepSeek technology and is provided for informational purposes only. When using the AI Assistant:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Do not share sensitive personal or confidential information</li>
              <li>Understand that responses are generated by AI and may not always be accurate</li>
              <li>Use the information provided at your own discretion</li>
            </ul>
          </section>
          
          <section>
            <h2 className="text-2xl font-semibold mb-4">Prohibited Activities</h2>
            <p className="mb-4">
              When using LINE.UP, you agree not to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe on the intellectual property rights of others</li>
              <li>Attempt to gain unauthorized access to any part of the service</li>
              <li>Use the service to distribute malware or harmful content</li>
              <li>Engage in any activity that could harm the service or other users</li>
            </ul>
          </section>
          
          <section>
            <h2 className="text-2xl font-semibold mb-4">Limitation of Liability</h2>
            <p>
              LINE.UP is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the service, including but not limited to direct, indirect, incidental, or consequential damages.
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-semibold mb-4">Changes to Terms</h2>
            <p>
              We may update these Terms of Service from time to time. We will notify you of any significant changes by posting the new Terms on this page and updating the "Last Updated" date.
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-semibold mb-4">Contact Us</h2>
            <p>
              If you have any questions about these Terms of Service, please contact us through our GitHub repository.
            </p>
          </section>
        </div>
        
        <div className="mt-12 text-sm text-gray-600 dark:text-gray-400">
          Last Updated: March 1, 2024
        </div>
      </div>
    </div>
  );
};

export default TermsOfService; 